name: CI - Build and Compose Up   

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build all services
        run: docker-compose -f docker-compose.yml build

      - name: Start all containers
        run: docker-compose -f docker-compose.yml up -d

      - name: Verify containers are running
        run: docker ps -a

      - name: Tear down environment
        if: always()
        run: docker-compose -f docker-compose.yml down
